<?php

return [
	[
		'name'     => 'siteName',
		'type'     => 'Text',
		'label'    => 'site-name',
		'required' => true,
		'filters'  => ['string', 'trim'],
		'class'    => 'uk-input uk-width-medium',
	],
	[
		'name'    => 'siteOffline',
		'type'    => 'Switcher',
		'label'   => 'site-offline',
		'value'   => 'Y',
		'filters' => ['yesNo'],
	],
	[
		'name'    => 'siteOfflineMsg',
		'type'    => 'TextArea',
		'label'   => 'offline-message',
		'rows'    => 3,
		'cols'    => 15,
		'value'   => 'This site is down for maintenance.<br />Please check back again soon.',
		'showOn'  => 'siteOffline:Y',
		'filters' => ['basicHtml'],
		'class'   => 'uk-textarea uk-width-medium',
	],
	[
		'name'    => 'listLimit',
		'type'    => 'Number',
		'label'   => 'default-list-limit',
		'min'     => 1,
		'value'   => 15,
		'filters' => ['uint'],
		'class'   => 'uk-input uk-width-medium',
	],
	[
		'name'    => 'siteMetaDesc',
		'type'    => 'TextArea',
		'label'   => 'site-meta-desc',
		'rows'    => 3,
		'cols'    => 15,
		'filters' => ['string', 'trim'],
		'class'   => 'uk-textarea uk-width-medium',
	],
	[
		'name'    => 'siteMetaKeys',
		'type'    => 'TextArea',
		'label'   => 'site-meta-keys',
		'rows'    => 3,
		'cols'    => 15,
		'filters' => ['string', 'trim'],
		'class'   => 'uk-textarea uk-width-medium',
	],
	[
		'name'    => 'siteRobots',
		'type'    => 'Select',
		'label'   => 'robots',
		'options' => [
			''                  => 'robot-index-follow',
			'noindex, follow'   => 'robot-no-index-follow',
			'index, nofollow'   => 'robot-index-no-follow',
			'noindex, nofollow' => 'robot-no-index-no-follow',
		],
		'rules'   => ['Options'],
		'class'   => 'uk-select uk-width-medium',
	],
	[
		'name'    => 'siteContentRights',
		'type'    => 'TextArea',
		'label'   => 'content-rights',
		'rows'    => 3,
		'cols'    => 15,
		'filters' => ['string', 'trim'],
		'class'   => 'uk-textarea uk-width-medium',
	],
];