version: "3"

services:
  ubuntu-22.04:
    build: .
    volumes:
      - ./:/var/www/hummingbird.local
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - 9000:80
      - 2053:2053
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - 6603:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hummingbird_cms
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
